# Styles the code properly

default_language_version:
    python: python3

# List of super useful formatters.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # Ensures the code is syntaxically correct
  - id: check-ast
  # Ensures a file name will resolve on all platform
  - id: check-case-conflict
  # Checks files with the execute bit set have shebangs
  - id: check-executables-have-shebangs
  # Ensure there's no incomplete merges
  - id: check-merge-conflict
  # Make sure yml files are formatted properly.
  - id: check-yaml
  # Adds an empty line if missing at the end of a file.
  - id: end-of-file-fixer
  # Makes sure requirements.txt is properly formatted
  - id: requirements-txt-fixer
  # Removes trailing whitespaces.
  - id: trailing-whitespace
# Leave black at the bottom so all touchups are done before it is run.
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
