# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# This is a very simple build pipeline for now. It simply validates that the code
# adheres to the Black code style and passes flake8.
jobs:
- job: code_style_validation
  displayName: Code Style Validation
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  # Install all the Python code validation packages.
  - bash: python -m pip install black flake8
    displayName: Install validators
  # Ensure the code that was pushed has the proper formatting, except in the
  # ui folder.
  - bash: black --check . --exclude="i\/.*py$"
    displayName: black
  # We'll check also that the code is flake8 compliant.
  # We're excluding E203 as black has a different mind about white spaces when using
  # slices than PEP8. black also uses 88 as the max line length, so use that so
  # code comments are properly formatted.
  - bash: flake8 --extend-ignore=E203 --exclude="*/ui/*.py" --max-line-length=88
    displayName: flake8

# Runs all tests using pytest
- job: run_tests
  displayName: Tests
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - bash: python -m pip install pytest
  # Runs tests only if there is a test folder, otherwise displays "No test to run."
  - bash: (test -r tests && pytest) || echo "No test to run"
