# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # comma separated list of globs that exclude files from flake8 validation
  flake8_exclude: ""
  # space separated list of Python packages that need to be pip installed.
  extra_pip_dependencies: ""
  # If true, the unit tests will be skipped
  skip_tests: true


# This build pipeline will validate the code style and our test suite on
# multiple platforms.
jobs:

- template: "templates/code-style-validation.yml"
  parameters:
    flake8_exclude: ${{ parameters.flake8_exclude }}

# Do not include tests if user requested to skip them
- if ${{ eq( parameters.skip_tests, true ) }}:
  - template: "templates/unit-tests.yml"
    parameters:
      extra_pip_dependencies: ${{ parameters.extra_pip_dependencies }}

# FIXME: We should find a way to avoid including this step on forked repos.
# Only launch a build on a tag.
- ${{ if startsWith( variables['Build.SourceBranch'], 'refs/tags') }}:
  - template: "templates/release-to-appstore.yml"
