# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  flake8_exclude: ""

# This is a very simple build pipeline for now. It simply validates that the code
# adheres to the Black code style and passes flake8.
jobs:
- job: code_style_validation
  displayName: Code Style Validation
  pool:
    vmImage: 'ubuntu-16.04'
  steps:

  # Use Python 3 for validating the code.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  # Install all the Python code validation packages.
  - bash: python -m pip install black flake8
    displayName: Install validators

  # Ensure the code that was pushed has the proper formatting, except in the
  # ui folder, which is auto-generated.
  - bash: black --check . --exclude="i\/.*py$"
    displayName: black

  - bash: echo ${{ variables['System.PullRequest.TargetBranch'] }}
    condition: always()

  # We do a diff against the branch. We do not tolerate any flake8 errors on new code, so validate it.
  - bash: |
      git diff $SYSTEM_PULLREQUEST_TARGETBRANCH |
      flake8 --diff --extend-ignore=E203 --exclude="*/ui/*.py,$FLAKE8_EXCLUDE" --max-line-length=88
    displayName: flake8 of diff
    # We only run flake8 on a pull request, since only then do we know which lines are
    # modified and should be flake8ed.
    condition: eq(variables['Build.Reason'], 'PullRequest')
