# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # Git ref of tk-toolchain to use.
  tk_toolchain_ref: master

jobs:
# Spin up a Linux VM for validating code.
- job: code_style_validation
  displayName: Code Style Validation
  pool:
    vmImage: 'ubuntu-16.04'
  steps:

  # Use Python 3 for validating the code.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  # Install all the Python code validation packages.
  - bash: |
      python -m pip install pre-commit &&
      pre-commit run --all
    displayName: Validate code

  - bash:
      # PySide 2 and tk-toolchain are required to build the documentation.
      pip install PySide2 git+https://github.com/shotgunsoftware/tk-toolchain.git@${{ parameters.tk_toolchain_ref }}#egg=tk-toolchain &&
      git clone https://github.com/shotgunsoftware/tk-core --depth 1 --branch SG-13264-python-3-compat ../tk-core
      tk-docs-preview --build-only --verbose
    displayName: Validate documentation
