# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.



jobs:
- job: release_to_appstore
  displayName: Release to AppStore
  pool:
    vmImage: 'ubuntu-16.04'
  steps:

  # Switch to the right Python Version.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 2.7
    displayName: Use Python 2.7

  # This task can be executed only from the shotgunsoftware
  # organization repositories. It will fail on forks on our
  # repos from other users.
  #
  # Therefore, the azure_internal_deploy_key is safely
  # stored in Azure Pipelines.
  #
  # Excerpt from https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks
  #
  # By default with GitHub pipelines, secrets associated with
  # your build pipeline are not made available to pull request
  # builds of forks. These secrets are enabled by default with
  # GitHub Enterprise Server pipelines. Secrets include:
  #
  # - A security token with access to your GitHub repository.
  # - These items, if your build uses them:
  #   - Service connection credentials
  #   - Files from the secure files library (this is what 'azure_internal_deploy_key' is)
  #   - Build variables marked secret
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      # This is the public key
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2Lqh+PhBOBwpKTAsUpbKmcG2SlXXWilBu0BP8XZ8yHKsYrh6DLU2COrh3ydSgeiUu/CGdpE701bVgym/pU8q12Ak387rgM50B3jEa+tpurQgf3Bx46W2T7BKcFH0bBkEworrd3RsVDKwVVXVjnsgIR4iViq5kJXlglakc8TtzBhRLfhtcqWSr8pyNFWP4bT0zW+uK3VpTsA2IdrI56iDe/aIe/IIFfITYfdbPa/+jzahWaPykoShvZB4YR+2W0em7JirZlemWWFKHqVRarcfHnmxGoJUKZ6y2L5I1FVkSt9gcXREIabPi8YmGGP6daw8KALSWzc6EoiQPz/ph78hH boismej@C02XKB07JG5J
      #sshPassphrase: # Optional
      sshKeySecureFile: azure_internal_deploy_key

  - bash: git clone --depth 1 git@github.com:$DEPLOY_REPO ../deploy_scripts
    env:
      DEPLOY_REPO: $(Deploy.Repo)
