# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

jobs:
  # Launch a Linux VM
- job: release_to_appstore
  displayName: Release to AppStore
  pool:
    vmImage: 'ubuntu-16.04'
  steps:

  # Switch to the right Python Version.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 2.7
    displayName: Use Python 2.7

  # This task can be executed only from the "shotgunsoftware"
  # organization repositories. It will fail on forks of our
  # repos from other users.
  #
  # Therefore, the appstore release scripts in app_store.zip
  # are safe from the outside world.
  #
  # Excerpt from https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks
  #
  # By default with GitHub pipelines, secrets associated with
  # your build pipeline are not made available to pull request
  # builds of forks. These secrets are enabled by default with
  # GitHub Enterprise Server pipelines. Secrets include:
  #
  # - A security token with access to your GitHub repository.
  # - These items, if your build uses them:
  #   - Service connection credentials
  #   - Files from the secure files library (this is what 'azure_internal_deploy_key' is)
  #   - Build variables marked secret
  - task: DownloadSecureFile@1
    name: app_store_zip
    inputs:
      secureFile: app_store.zip
    displayName: Download release scripts

  - bash: |
      unzip $(app_store_zip.secureFilePath) -d .. &&
      pip install -r ../app_store/requirements.txt
    displayName: Prepare release scripts

  # Deploy the bundle to the Toolkit AppStore.
  - bash: |
      export BUNDLE_TYPE=`python -c '
      import os
      # Detects the bundle type by looking at the python file at the root of the repo.
      repo = os.path.basename(os.getcwd())
      if os.path.exists("app.py"):
          print("app")
      elif os.path.exists("framework.py"):
          print("framework")
      elif os.path.exists("engine.py"):
          print("engine")
      else:
          print("config")
      '`
      python ../app_store/bundle_to_app_store.py --repository $(Build.DefinitionName) --bundle-type $BUNDLE_TYPE --no-ftp --use-https --tag $(Build.SourceBranchName)
    env:
      # Just like the DownloadSecureFile, the environment variables here can only
      # be used from builds on shotgunsoftware, not from forks, so we do not have
      # to worry about our credentials leaking to clients, nor do we have to
      # worry about clients pushing code to our appstore from their pull requests.
      sgtk_app_store_api_server: $(sgtk_app_store_api_server)
      sgtk_app_store_api_user: $(sgtk_app_store_api_user)
      sgtk_app_store_api_key: $(sgtk_app_store_api_key)
    displayName: Deploy Toolkit bundle to AppStore
