# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.



jobs:
- job: release_to_appstore
  displayName: Release to AppStore
  pool:
    vmImage: 'ubuntu-16.04'
  steps:

  # Switch to the right Python Version.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 2.7
    displayName: Use Python 2.7

  # This task can be executed only from the shotgunsoftware
  # organization repositories. It will fail on forks on our
  # repos from other users.
  #
  # Therefore, the azure_internal_deploy_key is safely
  # stored in Azure Pipelines.
  #
  # Excerpt from https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks
  #
  # By default with GitHub pipelines, secrets associated with
  # your build pipeline are not made available to pull request
  # builds of forks. These secrets are enabled by default with
  # GitHub Enterprise Server pipelines. Secrets include:
  #
  # - A security token with access to your GitHub repository.
  # - These items, if your build uses them:
  #   - Service connection credentials
  #   - Files from the secure files library (this is what 'azure_internal_deploy_key' is)
  #   - Build variables marked secret
  - task: DownloadSecureFile@1
    name: app_store_release_zip # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
    inputs:
      secureFile: app_store_release.zip

  - bash: unzip $(app_store_release_zip.secureFilePath) -d ..

  - bash: pip install -r ../app_store/requirements.txt

  - bash: python ../app_store/bundle_to_app_store.py
