# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  flake8_exclude: ""

jobs:
- job: unit_tests  # name of the job, A-Z, a-z, 0-9, and underscore
  strategy:
    matrix:
      Linux:
        image_name: 'ubuntu-16.04'
        qt_libs_2_7: PySide
        qt_libs_3: PySide2
      macOS:
        image_name: 'macos-10.13'
        qt_libs_2_7: PySide2
        qt_libs_3: PySide2
      Windows:
        image_name: 'vs2017-win2016'
        qt_libs_2_7: PySide
        qt_libs_3: PySide2
  pool:
    vmImage: $(image_name)
  steps:
    - template: unit_tests_with.yml
      parameters:
        qt_libs: qt_libs_2_7
        python_version: 2.7
    - template: unit_tests_with.yml
      parameters:
        qt_libs: qt_libs_3
        python_version: 3.7
