# Copyright (c) 2025 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # Git ref of tk-toolchain to use.
  tk_toolchain_ref: ticket/SG-41463
  # Git ref of tk-core to use.
  tk_core_ref: master

jobs:
# Spin up a Linux VM for validating code.
- job: build_documentation
  displayName: Build Sphinx Documentation
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    inputs:
      versionSpec: "3.10"

  - template: pip-install-packages.yml
    parameters:
      packages:
      - ${{ if startsWith( variables['Build.SourceBranch'], 'tk-' ) }}:
        - PySide2
      - https://github.com/shotgunsoftware/tk-toolchain/archive/${{ parameters.tk_toolchain_ref }}.zip

  - ${{ if startsWith( variables['Build.SourceBranch'], 'tk-' ) }}:
    - template: clone-repositories.yml
      parameters:
        repositories:
        - name: tk-core
          ref: ${{ parameters.tk_core_ref }}

  - task: Bash@3
    displayName: Build Shpinx Documentation
    inputs:
      targetType: inline
      script: tk-docs-preview --build-only --verbose
