# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # Git ref of tk-toolchain to use.
  tk_toolchain_ref: master
  # Git ref of tk-core to use.
  tk_core_ref: master

jobs:
- job: code_style_validation
  displayName: Code Style Validation
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3.11
    inputs:
      versionSpec: "3.11"

  - template: pip-install-packages.yml
    parameters:
      packages:
      - pre-commit

  - bash: pre-commit autoupdate
    displayName: Update pre-commit hook versions

  - bash: pre-commit run --all
    displayName: Validate code

  - script: |
      build_sphinx_docs="true"
      [ -d "$(Build.SourcesDirectory)/docs" ] || build_sphinx_docs="false"

      echo "##vso[task.setvariable variable=build_sphinx_docs;isOutput=true]${build_sphinx_docs}"
      echo "Will build the Sphinx documentation? ${build_sphinx_docs}"
    name: detect_docs
    displayName: Detect if the documentation folder exists

- job: build_documentation
  displayName: Build Sphinx Documentation
  dependsOn: code_style_validation
  variables:
    build_sphinx_docs: $[ dependencies.code_style_validation.outputs['detect_docs.build_sphinx_docs'] ]

  condition: |
    and(
      ne(variables['build_sphinx_docs'], false),
      not(
        startsWith( variables['Build.SourceBranch'], 'refs/tags')
      )
    )

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    inputs:
      versionSpec: "3.10"

  - template: pip-install-packages.yml
    parameters:
      packages:
      - https://github.com/shotgunsoftware/tk-toolchain/archive/${{ parameters.tk_toolchain_ref }}.zip
      - ${{ if eq( variables['Build.DefinitionName'], 'sg-jira-bridge' ) }}:
        - --requirement requirements.txt
      - ${{ if startsWith( variables['Build.DefinitionName'], 'tk-' ) }}:
        - PySide2

  - ${{ if startsWith( variables['Build.DefinitionName'], 'tk-' ) }}:
    - template: clone-repositories.yml
      parameters:
        repositories:
        - name: tk-core
          ref: ${{ parameters.tk_core_ref }}

  - task: Bash@3
    displayName: Build Sphinx Documentation
    inputs:
      targetType: inline
      script: tk-docs-preview --build-only --verbose
