# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # Version of tk-toolchain to use.
  tk_toolchain_ref: master
  # Version of the release repository to use.
  # This is meant for deployment to the Toolkit AppStore. This repository is private
  # to the Shotgun team and cannot be accessed by external organizations. This is meant
  # for internal use by the team for testing and should not be modified otherwise.
  release_repo_ref: master

jobs:
- job: release_toolkit_bundle
  displayName: Release Toolkit bundle
  pool:
    vmImage: ubuntu-latest
  steps:
    # Switch to the right Python Version.
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.10
      displayName: Use Python 3.10

    - template: configure-git.yml

    # Pushes the bundle to the appstore.
    - template: release-to-appstore.yml
      parameters:
        release_repo_ref: ${{ parameters.release_repo_ref }}

    # We need tk-toolchain to use update-configurations.yml
    - template: pip-install-packages.yml
      parameters:
        packages:
        - https://github.com/shotgunsoftware/tk-toolchain/archive/${{ parameters.tk_toolchain_ref }}.zip

    # Updates the basic, default2 and flame configs
    - template: "update-configuration.yml"
      parameters:
        name: tk-config-basic

