# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # Version of tk-toolchain to use.
  tk_toolchain_ref: master

jobs:
  # Launch a Linux VM
- job: release_toolkit_bundle
  displayName: Release Toolkit bundle
  pool:
    vmImage: 'macos-10.13'
  steps:
    # Switch to the right Python Version.
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 2.7
      displayName: Use Python 2.7

    # We need tk-toolchain to release packages.
    - template: pip-install-packages.yml
      parameters:
        packages:
        - git+https://github.com/shotgunsoftware/tk-toolchain.git@${{ parameters.tk_toolchain_ref }}#egg=tk-toolchain

    # - template: release-to-appstore.yml

    # We need to update the basic and default2 configs.

    # Updates the basic config.
    - template: "update-configuration.yml"
      parameters:
        name: tk-config-basic
        secure_file: basic-repo-deploy-key
        public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqsgPqp2HffphwE1l/oeYOkOmRyXNYKBffsniGJHN4Fjf6yLU7jCiTvYXW6ZkjEmDn295BMuaWFGl3CWN5A+2wHImXfunxPyqiwI27/UEa5MHR0iPsrL29vr68fipQMAlgy0ecDhkHJ+u9lom7+dJiw7xSBYy4cVKec6+ame7yl9RyQQO7RTOSmmyWBskyRKtDv64AbKV0cZ/oVhiiDpxhAADIHjDWKGVwRjaChJrzuIqS3hiyGbCBWFnWZZ+5ztGKPvfsGysS1AncC1r09ovf3GdCzx2F/liSe2MmzhcpJXepznrDbn/hwtrLgp8yK6NoaYzxHaMSm5owrK1LD+RD
        known_host: github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

    # Updates the default2 config
    - template: "update-configuration.yml"
      parameters:
        name: tk-config-default2
        secure_file: default2-repo-deploy-key
        public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGp4R0o0hyNlbIPily+i4vUjH8VJTiwgMtCLGf6gKGHubmIWz6tvlyvYjMvh56QosyfR4/7CG6xhQVghg65uaAldGA6usI388soPEq6qsX1aGhhpYpNzUsRjoDLSOPixRac0wCvCmhoOxMaIqwrOI12hD4kxMbTZ2DLt+v2OVg1XpkphVoQ5q5EY3u+syFDWU1ZSgjcd1kbAU6SxscF7CrXS0HCytO7YcyPr1NZ9Z4lnzVAXdT7QTsiC96HIhuFKfMTocD7nUnVxljRPvbIHtGsgE+0nE4fR1nxxMaw5jPsJ9EjxL9UBcUxVlUliRki2Ae+69J7yxpOweUxfk51oO3
        known_host: github.com,140.82.113.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
