# Copyright (c) 2023 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

jobs:
# Spin up a Linux VM for validating code.
- job: png_resources_validation
  displayName: PNG Resources Validation
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - script: |
        sudo apt update
        sudo apt install -y build-essential
        wget https://downloads.sourceforge.net/project/pmt/pngcrush/1.8.13/pngcrush-1.8.13.tar.gz
        tar xzf pngcrush-1.8.13.tar.gz
        cd pngcrush-1.8.13
        make
        sudo mv pngcrush /usr/local/bin
      displayName: 'Install Dependencies'
    - script: |
        # Initialize error counter and error messages
        errors=0
        error_messages=""    

        # Run pngcrush command on PNG files and check for errors
        for file in $(find . -type f -name "*.png"); do
          output=$(pngcrush -n -q "$file" 2>&1)
          echo "$output"
          if [[ "$output" == *"pngcrush: iCCP"* ]]; then
              errors=$((errors + 1))
              error_messages+="$output\n"
          fi
        done
        
        # If there were any errors, print custom message and error messages
        if [ $errors -gt 0 ]; then
          echo -e "\nThe following PNG files have profile errors. Consider using an optimizing PNG image tool like mogrify to fix or strip the incorrect profiles:\n"
          echo -e "$error_messages"
          exit $(($errors > 254 ? 254 : $errors))
        fi
      displayName: 'Process PNG files using pngcrush'
      workingDirectory: $(Build.SourcesDirectory)/resources
