# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # Git ref of tk-toolchain to use.
  tk_toolchain_ref: master
  # Git ref of tk-core to use.
  tk_core_ref: master

jobs:
# Spin up a Linux VM for validating code.
- job: png_resources_validation
  displayName: PNG Resources Validation
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - script: |
        sudo apt update
        sudo apt install -y pngcrush
      displayName: 'Install Dependencies'
    - script: |
        # Print the full paths of PNG files
        find . -type f -name "*.png" -print
        # Run pngcrush command on PNG files and check for Profile issues
        for file in $(find . -type f -name "*.png"); do
          output=$(pngcrush -n -q "$file" 2>&1)
          echo "$output"
          if [[ "$output" == *"pngcrush: iCCP:"* ]]; then
            echo "Warning processing file $file"
            exit 1
          fi
        done
      displayName: 'Process PNG files using pngcrush'
      workingDirectory: $(Build.SourcesDirectory)/resources
