# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # List of Python packages that need to be pip installed for testing.
  extra_test_dependencies: []
  # Git ref of tk-toolchain to use.
  tk_toolchain_ref: master
  # List of repositories to clone alongside this repository.
  # To clone the tk-framework-shotgunutils's master branch
  # and a specific tk-framework-qtwidget ref, you would
  # set this parameter to the following:
  # - name: tk-framework-shotgunutils
  # - name: tk-framework-qtwidgets
  #   ref: <branch-or-tag>
  additional_repositories: []
  # Git ref of tk-core to use.
  tk_core_ref: master
  # Post test steps
  # This is a list of Azure Pipeline steps that will be inserted
  # right after the tests were run.
  # If you wanted to run a non-standard suite of test as an extra
  # you would specify post_tests_steps as:
  # post_tests_steps:
  # - bash: do_something
  # - bash: do_something_else
  post_tests_steps: []
  # If set to true, the build agent will run unit tests.
  has_unit_tests: true

  vfx_reference_platform_versions:
    - name: VFX CY2022
      python_version: '3.9'
      qt_wrapper: PySide2==5.15.2.1

    - name: VFX CY2023
      python_version: '3.10'
      qt_wrapper: PySide2==5.15.2.1

    - name: VFX CY2024
      python_version: '3.11'
      qt_wrapper: PySide6

  os_versions:
    - name: Windows
      vm_image: windows-2022
      codecov_download_url: https://uploader.codecov.io/latest/windows/codecov.exe

    - name: Linux
      vm_image: ubuntu-22.04
      codecov_download_url: https://uploader.codecov.io/latest/linux/codecov

    - name: macOS
      vm_image: macOS-14
      codecov_download_url: https://uploader.codecov.io/v0.7.3/macos/codecov
      # macOS & codecov note:
      # In Nov 2024 (SG-36700), we pinned macOS to codecov v0.7.3 because the
      # macOS-14 Azure Pipelines agent is Intel (x86_64), but Codecov started
      # shipping arm64-only binaries.
      # When we will change the macOs image to a arm64 arch, we can use the
      # "latest" version again.

jobs:
  - ${{ if eq( parameters.has_unit_tests, true ) }}:
    - ${{ each os_version in parameters.os_versions }}:
      - ${{ each platform in parameters.vfx_reference_platform_versions }}:
        - template: run-tests-with.yml
          parameters:
            codecov_download_url: ${{ os_version.codecov_download_url }}
            os_name: ${{ os_version.name }}
            python_version: ${{ platform.python_version }}
            qt_wrapper: ${{ platform.qt_wrapper }}
            vm_image: ${{ os_version.vm_image }}

            # pass through all parameters
            extra_test_dependencies: ${{ parameters.extra_test_dependencies }}
            tk_toolchain_ref: ${{ parameters.tk_toolchain_ref }}
            additional_repositories: ${{ parameters.additional_repositories }}
            tk_core_ref: ${{ parameters.tk_core_ref }}
            post_tests_steps: ${{ parameters.post_tests_steps }}
