# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  # Name of the virtual machine image to load.
  image_name: ""
  # Name of the Qt wrapper to pip install. Should be PySide or PySide2
  qt_wrapper: ''
  # Python version to use.
  python_version: ''
  # List of Python packages that need to be pip installed for testing.
  extra_test_dependencies: []
  # Pretty name for the OS.
  os_name: ""
  # Git ref of tk-toolchain to use.
  tk_toolchain_ref: master
  # List of repositories to clone alongside this repository.
  # To clone the tk-framework-shotgunutils's master branch
  # and a specific tk-framework-qtwidget ref, you would
  # set this parameter to the following:
  # - name: tk-framework-shotgunutils
  # - name: tk-framework-qtwidgets
  #   ref: <branch-or-tag>
  additional_repositories: []
  # Git ref of tk-core to use.
  tk_core_ref: master
  # Post test steps
  # This is a list of Azure Pipeline steps that will be inserted
  # right after the tests were run.
  # If you wanted to run a non-standard suite of test as an extra
  # you would specify post_tests_steps as:
  # post_tests_steps:
  # - bash: do_something
  # - bash: do_something_else
  post_tests_steps: []

jobs:
- job:
  displayName: ${{ parameters.os_name }} Python ${{ parameters.python_version }}
  pool:
    vmImage: ${{ parameters.image_name }}
  steps:

  # Switch to the right Python Version.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.python_version }}
    displayName: Use Python ${{ parameters.python_version }}

  - template: pip-install-packages.yml
    parameters:
      packages:
      - ${{ parameters.qt_wrapper }}
      - https://github.com/shotgunsoftware/tk-toolchain/archive/${{ parameters.tk_toolchain_ref }}.zip
      - pytest
      - pytest-cov
      - pytest-nunit
      # Inserting a parameter that is a list into another list flattens
      # the result instead of nesting it.
      # E.g. given a extra_test_dependencies parameter set to [Qt.py, numpy], the packages
      # parameter will end up as
      # - PySide2
      # - git+https://github.com/shotgunsoftware/tk-toolchain.git@${{ parameters.tk_toolchain_ref }}#egg=tk-toolchain
      # - pytest-azurepipelines
      # - Qt.py
      # - numpy
      - ${{ parameters.extra_test_dependencies }}

  - script: |
      pip --version
      pip list
    displayName: Check installed packages

  - template: clone-repositories.yml
    parameters:
      repositories:
      - name: tk-core
        ref: ${{ parameters.tk_core_ref }}
      # Nested lists are flattened, as explained above in pip-install-packages.yml.
      - ${{ parameters.additional_repositories }}

  # We can't use eq(Agent.OS, 'linux') here because template expansion is done
  # before the job is assigned to an agent.
  - ${{ if contains(parameters.image_name, 'ubuntu') }}:
    # Start xvfb on Linux so we can test with a GUI.
    - bash: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started Xvfb"
      displayName: Start Xvfb

    - bash: sudo apt update
      displayName: APT Update

    # Install libegl1 required for PySide6
    - bash: sudo apt install libegl1
      displayName: Install libegl1

  # Repositories using our build pipeline outside of the
  # shotgunsoftware organization should not be able to run our UI automation
  # so do not clone the ui automation in that case.
  #
  # Therefore, we need to avoid including this template for repos that are
  # not under the shotgunsoftware organization.
  #
  # FIXME: There is no way to tell if an Azure build is running under
  # our organization or not. What we can do however is check the name
  # of the Azure project from which this build is launched. This means a client could
  # in theory have a project named Toolkit and run these commands. In practice however,
  # all tests tasks require access to our secrets so they can't be used and the build will
  # fail.

  # Run the tests. The task will create a simple coverage file if one is missing.
  # It will include all code except for the "tests" folder.
  - bash: |
      if [ -e .coveragerc ]; then
        echo ".coveragerc was found."
      else
        cat > .coveragerc <<EOF
        [run]
        source=.
        omit=tests/*
        [report]
        exclude_lines = raise NotImplementedError
        EOF
        echo "Generated .coveragerc"
      fi

      python -m pytest \
        tests \
        --cov \
        --cov-report xml \
        --nunit-xml=test-results.xml \
        --verbose \

    # These environment variables need to be set so Linux runs can connect
    # to xvfb and to have complete logging. Each test logging output will
    # be captured by pytest and displayed on failure.
    env:
      QT_QPA_PLATFORM: offscreen
      DISPLAY: ':99.0'
      TK_DEBUG: 1
      CI: 1

      COVERAGE_FILE: .coverage.tests
      # Note that we're hardcoding the name of the coverage file. This is important
      # as "coverage combine" will combine all coverage files that match .coverage.*.
      # The parameters.post_tests_steps might also produce coeverage files

      # Allows to connect to a real Shotgun site during a test. Use sparingly to avoid
      # slowing down automation. Using Mockgun is still the best way to have speedy tests.
      TK_TOOLCHAIN_HOST: $(sg.ci.host)
      TK_TOOLCHAIN_USER_LOGIN: $(sg.ci.human.login)
      TK_TOOLCHAIN_USER_PASSWORD: $(sg.ci.human.password)
      SHOTGUN_TEST_ENTITY_SUFFIX: '$(Agent.Name)'
    displayName: Run tests

  # The post_test_steps list will be flattened into this list of steps.
  - ${{ parameters.post_tests_steps }}

  # We're done testing.. Before we can upload code coverage, we'll have to
  # combine the results.
  - task: Bash@3
    displayName: Combine code coverage results
    inputs:
      targetType: inline
      script: |
        python -m coverage combine

        python -m coverage xml -i
      # We need to pass in -i because we had some weird coverage entries for our frameworks and apps (tk-core is not affected)
      # We have an <path-to-the-repo>/(builtin) and <path-to-the-repo>/pyscript entries in the coverage for which the xml
      # genearte would generate errors otherwise since these are not actual source files

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: test-results.xml
      testRunTitle: "${{ parameters.os_name }} - Python ${{ parameters.python_version }}"
      failTaskOnFailureToPublishResults: true
      failTaskOnMissingResultsFile: true
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@2
    displayName: Publish code coverage
    inputs:
      summaryFileLocation: coverage.xml
      failIfCoverageEmpty: true

  # Upload the code coverage result to codecov.io using the binary uploader.
  # Use flags to identify coverage from each OS/Python combination for proper merging.
  #
  - task: Bash@3
    displayName: Uploading coverage to Codecov.io
    inputs:
      targetType: inline
      script: |
        curl -Os "${{ variables.codecov_download_url }}"
        chmod +x codecov
        ./codecov  \
          --file coverage.xml \
          --flags ${{ parameters.os_name }} \
          --flags Python-${{ parameters.python_version }} \
