# Copyright (c) 2019 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

parameters:
  name: ""
  secure_file: ""
  public_key: ""
  tk_toolchain_ref: master

steps:
# Switch to the right Python Version.
- task: UsePythonVersion@0
  inputs:
    versionSpec: 2.7
  displayName: Use Python 2.7

# This task can be executed only from the "shotgunsoftware"
# organization repositories. It will fail on forks of our
# repos from other users.
#
# Therefore, the appstore release scripts in app_store.zip
# are safe from the outside world.
#
# Excerpt from https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks
#
# By default with GitHub pipelines, secrets associated with
# your build pipeline are not made available to pull request
# builds of forks. These secrets are enabled by default with
# GitHub Enterprise Server pipelines. Secrets include:
#
# - A security token with access to your GitHub repository.
# - These items, if your build uses them:
#   - Service connection credentials
#   - Files from the secure files library (this is what 'azure_internal_deploy_key' is)
#   - Build variables marked secret
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    # This is the public key
    sshPublicKey: ${{ parameters.public_key }}
    #sshPassphrase: # Optional
    sshKeySecureFile: ${{ parameters.secure_file }}

# The configuration update script is in tk-toolchain
- template: pip-install-packages.yml
  parameters:
    packages:
    - git+https://github.com/shotgunsoftware/tk-toolchain.git@${{ parameters.tk_toolchain_ref }}#egg=tk-toolchain

# Run the update tool for the given bundle and tag.
- bash: |
    tk-config-update git@github.com:shotgunsoftware/${{ parameters.name }}.git $(Build.DefinitionName) $(Build.SourceBranchName) --push-changes
  displayName: Updating ${{ parameters.name }}
